-- ==============================================================================
-- SCRIPT SQL PARA CREAR LA TABLA UNIFICADA "GASTOS_DESPACHOS_2026" EN SUPABASE
-- Une los datos de las tablas: public.importaciones + public.gastos_importacion
-- ==============================================================================

-- 1. Crear la tabla unificada con todos los campos de importación y gastos
CREATE TABLE IF NOT EXISTS public."GASTOS_DESPACHOS_2026" (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Campos Principales de Identificación (Importaciones)
    n_referencia TEXT UNIQUE NOT NULL,
    n_declaracion TEXT,
    fecha_aceptacion TEXT,
    fecha_factura TEXT,
    razon_social TEXT,
    nit_importador TEXT,
    cliente_id UUID,
    aduana TEXT,
    factura TEXT,
    proveedor TEXT,
    modalidad TEXT,
    pedido TEXT,
    oi TEXT,
    oc TEXT,
    guia_embarque TEXT,
    contenedor TEXT,
    peso_bruto TEXT,
    tipo_cambio NUMERIC(10,4) DEFAULT 6.96,
    items TEXT,
    
    -- Totales y Tributos Aduaneros (Importaciones)
    total_cif NUMERIC(15,2) DEFAULT 0,
    gravamen NUMERIC(15,2) DEFAULT 0,
    iva NUMERIC(15,2) DEFAULT 0,
    total_tributos NUMERIC(15,2) DEFAULT 0,

    -- Desglose Completo de Gastos (gastos_importacion)
    honorarios_agencia NUMERIC(15,2) DEFAULT 0,
    carpeta_p_archivo NUMERIC(15,2) DEFAULT 0,
    gastos_en_despacho NUMERIC(15,2) DEFAULT 0,
    fotocopias_legalizadas NUMERIC(15,2) DEFAULT 0,
    verificacion_y_etiquetado NUMERIC(15,2) DEFAULT 0,
    regularizacion_desp_anticipad NUMERIC(15,2) DEFAULT 0,
    items_declarados_en_dim_y_dav NUMERIC(15,2) DEFAULT 0,
    despacho_aduana_frontera NUMERIC(15,2) DEFAULT 0,
    servicio_logistico NUMERIC(15,2) DEFAULT 0,
    formulario_dam NUMERIC(15,2) DEFAULT 0,
    otros_servicios NUMERIC(15,2) DEFAULT 0,
    formulario_ritex NUMERIC(15,2) DEFAULT 0,
    serv_de_tram_senasag_unalab NUMERIC(15,2) DEFAULT 0,
    ingreso_y_recojo_tram_senasag NUMERIC(15,2) DEFAULT 0,
    total_factura NUMERIC(15,2) DEFAULT 0,
    gravamen_arancelario NUMERIC(15,2) DEFAULT 0,
    impuesto_al_valor_agregado NUMERIC(15,2) DEFAULT 0,
    imp_al_consumo_espcifico NUMERIC(15,2) DEFAULT 0,
    imp_esp_a_los_hidrocarburos NUMERIC(15,2) DEFAULT 0,
    formulario_digital NUMERIC(15,2) DEFAULT 0,
    imp_al_con_espec_al_deporte NUMERIC(15,2) DEFAULT 0,
    levantamiento_de_abandono NUMERIC(15,2) DEFAULT 0,
    cam_ind_y_com NUMERIC(15,2) DEFAULT 0,
    recojo_guia NUMERIC(15,2) DEFAULT 0,
    emision_certificado NUMERIC(15,2) DEFAULT 0,
    transporte_local NUMERIC(15,2) DEFAULT 0,
    almacenaje_dab NUMERIC(15,2) DEFAULT 0,
    gastos_puerto NUMERIC(15,2) DEFAULT 0,
    senasag NUMERIC(15,2) DEFAULT 0,
    agemed NUMERIC(15,2) DEFAULT 0,
    almacenaje_albo_villazon NUMERIC(15,2) DEFAULT 0,
    permiso_e_inspeccion_senasag NUMERIC(15,2) DEFAULT 0,
    ibnorca_ibmetro NUMERIC(15,2) DEFAULT 0,
    inspeccion_previa NUMERIC(15,2) DEFAULT 0,
    escaneo_de_facturas NUMERIC(15,2) DEFAULT 0,
    contravenciones NUMERIC(15,2) DEFAULT 0,
    almacenaje_albo NUMERIC(15,2) DEFAULT 0,
    pago_prima_de_seguro NUMERIC(15,2) DEFAULT 0,
    serv_transporte NUMERIC(15,2) DEFAULT 0,
    reintergo_ga NUMERIC(15,2) DEFAULT 0,
    reintegro_iva NUMERIC(15,2) DEFAULT 0,
    reintegro_ice NUMERIC(15,2) DEFAULT 0,
    carguio_y_descarguio NUMERIC(15,2) DEFAULT 0,
    tramite_senasag_villazon NUMERIC(15,2) DEFAULT 0,
    liberacion_contenedor NUMERIC(15,2) DEFAULT 0,
    tramite_senasag NUMERIC(15,2) DEFAULT 0,
    flete_maritimo NUMERIC(15,2) DEFAULT 0,
    emision_de_b_l NUMERIC(15,2) DEFAULT 0,
    sobreestadias NUMERIC(15,2) DEFAULT 0,
    deposito_especial NUMERIC(15,2) DEFAULT 0,
    tramites_aduana NUMERIC(15,2) DEFAULT 0,
    analisis_laboratorio NUMERIC(15,2) DEFAULT 0,
    gto_puerto_aspb NUMERIC(15,2) DEFAULT 0,
    gtos_de_logistica NUMERIC(15,2) DEFAULT 0,
    comision_banco_liberacion NUMERIC(15,2) DEFAULT 0,
    serv_carguio_y_descarguio NUMERIC(15,2) DEFAULT 0,
    seguro NUMERIC(15,2) DEFAULT 0,
    proleche NUMERIC(15,2) DEFAULT 0,
    inspeccion_senasag NUMERIC(15,2) DEFAULT 0,
    total_planilla NUMERIC(15,2) DEFAULT 0
);

-- 2. Habilitar Seguridad a Nivel de Filas (RLS)
ALTER TABLE public."GASTOS_DESPACHOS_2026" ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de Permiso para Consulta, Inserción y Edición
DROP POLICY IF EXISTS "Permitir select a todos en GASTOS_DESPACHOS_2026" ON public."GASTOS_DESPACHOS_2026";
CREATE POLICY "Permitir select a todos en GASTOS_DESPACHOS_2026" 
ON public."GASTOS_DESPACHOS_2026" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir insert/update a todos en GASTOS_DESPACHOS_2026" ON public."GASTOS_DESPACHOS_2026";
CREATE POLICY "Permitir insert/update a todos en GASTOS_DESPACHOS_2026" 
ON public."GASTOS_DESPACHOS_2026" FOR ALL USING (true);

-- 4. POBLAR / MIGRAR TODOS LOS DATOS EXISTENTES (Uniendo por n_referencia)
INSERT INTO public."GASTOS_DESPACHOS_2026" (
    n_referencia,
    n_declaracion,
    fecha_aceptacion,
    fecha_factura,
    razon_social,
    nit_importador,
    cliente_id,
    aduana,
    factura,
    proveedor,
    modalidad,
    pedido,
    oi,
    oc,
    guia_embarque,
    contenedor,
    peso_bruto,
    tipo_cambio,
    items,
    total_cif,
    gravamen,
    iva,
    total_tributos,
    honorarios_agencia,
    carpeta_p_archivo,
    gastos_en_despacho,
    fotocopias_legalizadas,
    verificacion_y_etiquetado,
    regularizacion_desp_anticipad,
    items_declarados_en_dim_y_dav,
    despacho_aduana_frontera,
    servicio_logistico,
    formulario_dam,
    otros_servicios,
    formulario_ritex,
    serv_de_tram_senasag_unalab,
    ingreso_y_recojo_tram_senasag,
    total_factura,
    gravamen_arancelario,
    impuesto_al_valor_agregado,
    imp_al_consumo_espcifico,
    imp_esp_a_los_hidrocarburos,
    formulario_digital,
    imp_al_con_espec_al_deporte,
    levantamiento_de_abandono,
    cam_ind_y_com,
    recojo_guia,
    emision_certificado,
    transporte_local,
    almacenaje_dab,
    gastos_puerto,
    senasag,
    agemed,
    almacenaje_albo_villazon,
    permiso_e_inspeccion_senasag,
    ibnorca_ibmetro,
    inspeccion_previa,
    escaneo_de_facturas,
    contravenciones,
    almacenaje_albo,
    pago_prima_de_seguro,
    serv_transporte,
    reintergo_ga,
    reintegro_iva,
    reintegro_ice,
    carguio_y_descarguio,
    tramite_senasag_villazon,
    liberacion_contenedor,
    tramite_senasag,
    flete_maritimo,
    emision_de_b_l,
    sobreestadias,
    deposito_especial,
    tramites_aduana,
    analisis_laboratorio,
    gto_puerto_aspb,
    gtos_de_logistica,
    comision_banco_liberacion,
    serv_carguio_y_descarguio,
    seguro,
    proleche,
    inspeccion_senasag,
    total_planilla
)
SELECT 
    COALESCE(i.n_referencia, g.n_referencia) AS n_referencia,
    COALESCE(i.n_declaracion, g.n_declaracion) AS n_declaracion,
    i.fecha_aceptacion,
    g.fecha_factura,
    i.razon_social,
    i.nit_importador,
    i.cliente_id,
    i.aduana,
    i.factura,
    i.proveedor,
    i.modalidad,
    i.pedido,
    i.oi,
    i.oc,
    i.guia_embarque,
    i.contenedor,
    i.peso_bruto,
    COALESCE(i.tipo_cambio, 6.96),
    i.items,
    COALESCE(CAST(NULLIF(regexp_replace(i.total_cif, '[^0-9.]', '', 'g'), '') AS NUMERIC), 0),
    COALESCE(CAST(NULLIF(regexp_replace(i.gravamen, '[^0-9.]', '', 'g'), '') AS NUMERIC), 0),
    COALESCE(CAST(NULLIF(regexp_replace(i.iva, '[^0-9.]', '', 'g'), '') AS NUMERIC), 0),
    COALESCE(CAST(NULLIF(regexp_replace(i.total_tributos, '[^0-9.]', '', 'g'), '') AS NUMERIC), 0),
    COALESCE(g.honorarios_agencia, 0),
    COALESCE(g.carpeta_p_archivo, 0),
    COALESCE(g.gastos_en_despacho, 0),
    COALESCE(g.fotocopias_legalizadas, 0),
    COALESCE(g.verificacion_y_etiquetado, 0),
    COALESCE(g.regularizacion_desp_anticipad, 0),
    COALESCE(g.items_declarados_en_dim_y_dav, 0),
    COALESCE(g.despacho_aduana_frontera, 0),
    COALESCE(g.servicio_logistico, 0),
    COALESCE(g.formulario_dam, 0),
    COALESCE(g.otros_servicios, 0),
    COALESCE(g.formulario_ritex, 0),
    COALESCE(g.serv_de_tram_senasag_unalab, 0),
    COALESCE(g.ingreso_y_recojo_tram_senasag, 0),
    COALESCE(g.total_factura, 0),
    COALESCE(g.gravamen_arancelario, 0),
    COALESCE(g.impuesto_al_valor_agregado, 0),
    COALESCE(g.imp_al_consumo_espcifico, 0),
    COALESCE(g.imp_esp_a_los_hidrocarburos, 0),
    COALESCE(g.formulario_digital, 0),
    COALESCE(g.imp_al_con_espec_al_deporte, 0),
    COALESCE(g.levantamiento_de_abandono, 0),
    COALESCE(g.cam_ind_y_com, 0),
    COALESCE(g.recojo_guia, 0),
    COALESCE(g.emision_certificado, 0),
    COALESCE(g.transporte_local, 0),
    COALESCE(g.almacenaje_dab, 0),
    COALESCE(g.gastos_puerto, 0),
    COALESCE(g.senasag, 0),
    COALESCE(g.agemed, 0),
    COALESCE(g.almacenaje_albo_villazon, 0),
    COALESCE(g.permiso_e_inspeccion_senasag, 0),
    COALESCE(g.ibnorca_ibmetro, 0),
    COALESCE(g.inspeccion_previa, 0),
    COALESCE(g.escaneo_de_facturas, 0),
    COALESCE(g.contravenciones, 0),
    COALESCE(g.almacenaje_albo, 0),
    COALESCE(g.pago_prima_de_seguro, 0),
    COALESCE(g.serv_transporte, 0),
    COALESCE(g.reintergo_ga, 0),
    COALESCE(g.reintegro_iva, 0),
    COALESCE(g.reintegro_ice, 0),
    COALESCE(g.carguio_y_descarguio, 0),
    COALESCE(g.tramite_senasag_villazon, 0),
    COALESCE(g.liberacion_contenedor, 0),
    COALESCE(g.tramite_senasag, 0),
    COALESCE(g.flete_maritimo, 0),
    COALESCE(g.emision_de_b_l, 0),
    COALESCE(g.sobreestadias, 0),
    COALESCE(g.deposito_especial, 0),
    COALESCE(g.tramites_aduana, 0),
    COALESCE(g.analisis_laboratorio, 0),
    COALESCE(g.gto_puerto_aspb, 0),
    COALESCE(g.gtos_de_logistica, 0),
    COALESCE(g.comision_banco_liberacion, 0),
    COALESCE(g.serv_carguio_y_descarguio, 0),
    COALESCE(g.seguro, 0),
    COALESCE(g.proleche, 0),
    COALESCE(g.inspeccion_senasag, 0),
    COALESCE(g.total_planilla, 0)
FROM public.importaciones i
FULL OUTER JOIN public.gastos_importacion g 
    ON UPPER(TRIM(i.n_referencia)) = UPPER(TRIM(g.n_referencia))
ON CONFLICT (n_referencia) DO NOTHING;
