-- ============================================================================
-- SCRIPT DE BASE DE DATOS: CONSOLIDACIÓN MATRICIAL HORIZONTAL DE IMPORTACIONES Y FACTURAS
-- CLIENTE CORPORATIVO EXCLUSIVO: MINERA SAN CRISTOBAL S.A. (NIT: 1020415021)
-- TABLA FÍSICA DETALLE: public.mtodo
-- TABLA FÍSICA RESUMEN MENSUAL: public.resumen_mensual
-- VISTA DE PRESENTACIÓN REQUERIDA: public.v_matriz_liquidacion_horizontal
-- AUTOR: Ingeniero de Software Senior / Arquitecto de Base de Datos
-- ============================================================================

-- ============================================================================
-- 1. LIMPIEZA SEGURA DE VISTAS Y ESTRUCTURAS PREVIAS
-- ============================================================================
DROP VIEW IF EXISTS public.v_matriz_liquidacion_horizontal CASCADE;
DROP VIEW IF EXISTS public.v_resumen_mensual CASCADE;
DROP VIEW IF EXISTS public.v_dim_comisiones_minera CASCADE;
DROP TABLE IF EXISTS public.matriz_liquidacion_horizontal CASCADE;
DROP TABLE IF EXISTS public.resumen_mensual CASCADE;
DROP TABLE IF EXISTS public.mtodo CASCADE;
DROP TABLE IF EXISTS public.config_comisiones_minera CASCADE;
DROP TABLE IF EXISTS public.config_comisiones_especiales CASCADE;

-- ============================================================================
-- 1.5 MIGRACIONES DE ESQUEMAS PREVIAS (Parche de columnas faltantes)
-- ============================================================================
ALTER TABLE IF EXISTS public.historial_datos_minera ADD COLUMN IF NOT EXISTS comision numeric(15,2) NULL;

-- ============================================================================
-- 2. CREACIÓN SEGURA DE NUEVAS ESTRUCTURAS DE CONTROL ACCESORIAS Y CONFIGURABLES
-- ============================================================================

-- A. Tabla segura para aislar ID del cliente que solo gestiona Supabase
CREATE TABLE IF NOT EXISTS public.clientes_interno (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nit text NOT NULL UNIQUE,
    razon_social text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT clientes_interno_pkey PRIMARY KEY (id)
);

-- B. Tabla de Configuración de NITs de Proveedores para deconstrucción de QR
CREATE TABLE IF NOT EXISTS public.config_nits (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nit text NOT NULL UNIQUE,
    proveedor text NULL,
    codigo text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT timezone ('utc'::text, now()),
    CONSTRAINT config_nits_pkey PRIMARY KEY (id)
);

-- C. TABLA CONFIGURABLE 1: Rangos de Comisión de Minera (Edita aquí montos y porcentajes por CIF)
CREATE TABLE public.config_comisiones_minera (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cif_usd_min numeric(15,2) NOT NULL,
    cif_usd_max numeric(15,2) NOT NULL,
    porcentaje_comision numeric(5,4) NOT NULL DEFAULT 0.0000, -- e.g., 0.0030 para 0.30%
    comision_fija numeric(15,2) NOT NULL DEFAULT 0.00,       -- e.g., 600.00
    descripcion text NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT config_comisiones_minera_pkey PRIMARY KEY (id)
);

-- D. TABLA CONFIGURABLE 2: Comisiones Especiales (Edita aquí tarifas fijas como EXP)
CREATE TABLE public.config_comisiones_especiales (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_operacion text NOT NULL UNIQUE,                      -- e.g. 'EXP'
    comision_fija numeric(15,2) NOT NULL DEFAULT 0.00,        -- e.g. 700.00
    descripcion text NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT config_comisiones_especiales_pkey PRIMARY KEY (id)
);

-- E. Gastos de Puerto de ingreso manual (ASPB)
CREATE TABLE IF NOT EXISTS public.gastos_puertos_manual (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    importacion_id bigint NOT NULL,
    monto numeric(15,2) NOT NULL DEFAULT 0.00,
    comprobante text NULL,
    fecha text NULL,
    codigo_puerto text DEFAULT 'ASPB',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT gastos_puertos_manual_pkey PRIMARY KEY (id),
    CONSTRAINT fk_gastos_puertos_importaciones FOREIGN KEY (importacion_id) REFERENCES public.importaciones(id)
);

-- ============================================================================
-- F. TABLA FÍSICA DETALLE COMPLETA: "mtodo" 
-- ============================================================================
CREATE TABLE public.mtodo (
    interno text NOT NULL,
    importacion_id bigint NULL,
    fecha_dim text NULL,
    mes text NOT NULL DEFAULT '-',
    nit_cliente text NOT NULL DEFAULT '1020415021',
    dim_n_ro text NULL,
    modalidad text NULL,
    dim_reg text NULL,
    oi text NULL,
    tipo_cambio text NULL,
    cif_usd text NULL,
    porcentaje_comision text NULL,
    valor_cif_bs text NULL,
    comision_bob numeric(15,2) NULL,
    gravamen numeric(15,2) DEFAULT 0.00,
    iva numeric(15,2) DEFAULT 0.00,
    total_tributos numeric(15,2) DEFAULT 0.00,
    
    -- ALBO / DAB
    albo_monto numeric(15,2) NULL,
    albo_factura text NULL,
    albo_fecha text NULL,
    albo_enlace text NULL,
    albo_cod text NULL,
    albo_n_declaracion_imp text NULL,
    albo_doc_aduanero_fac text NULL,
    albo_verificado text NULL,
    
    -- INSPECCION PREVIA (IP)
    ip_monto numeric(15,2) NULL,
    ip_factura text NULL,
    ip_fecha text NULL,
    ip_enlace text NULL,
    ip_cod text NULL,
    ip_examen_previo_imp text NULL,
    ip_doc_aduanero_fac text NULL,
    ip_verificado text NULL,
    
    -- GUÍAS
    guias_monto numeric(15,2) NULL,
    guias_factura text NULL,
    guias_fecha text NULL,
    guias_enlace text NULL,
    guias_cod text NULL,
    guias_guia_embarque_imp text NULL,
    guias_ref_guia_fac text NULL,
    guias_verificado text NULL,
    
    -- PUERTOS
    puertos_monto numeric(15,2) NULL,
    puertos_comprobante text NULL,
    puertos_fecha text NULL,
    
    -- OTROS
    otros_monto numeric(15,2) NULL,
    otros_factura text NULL,
    otros_fecha text NULL,
    otros_enlace text NULL,
    otros_cod text NULL,
    
    -- PLANILLA EXCEL
    ref_excel text NULL,
    fecha_excel text NULL,
    debito_excel numeric(15,2) NULL,
    
    -- VERIFICACIONES
    verificado_suma text NULL DEFAULT 'NO VERIFICADO',
    verificado_saldos text NULL DEFAULT 'NO VERIFICADO',
    
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT mtodo_pkey PRIMARY KEY (interno)
);

-- ============================================================================
-- G. TABLA DE REGISTRO DE VERIFICACIONES Y AUDITORÍA
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.registro_verificaciones (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    tipo text NOT NULL,
    fecha_ejecucion timestamp with time zone DEFAULT timezone('utc'::text, now()),
    resumen jsonb NOT NULL,
    detalles jsonb NOT NULL,
    CONSTRAINT registro_verificaciones_pkey PRIMARY KEY (id)
);
ALTER TABLE public.registro_verificaciones ADD COLUMN IF NOT EXISTS tipo text;
ALTER TABLE public.registro_verificaciones ADD COLUMN IF NOT EXISTS fecha_ejecucion timestamp with time zone DEFAULT timezone('utc'::text, now());
ALTER TABLE public.registro_verificaciones ADD COLUMN IF NOT EXISTS resumen jsonb;
ALTER TABLE public.registro_verificaciones ADD COLUMN IF NOT EXISTS detalles jsonb;
ALTER TABLE public.registro_verificaciones DISABLE ROW LEVEL SECURITY;
NOTIFY pgrst, 'reload schema';

-- ============================================================================
-- H. TABLA FÍSICA RESUMEN: "resumen_mensual"
-- ============================================================================
CREATE TABLE public.resumen_mensual (
    mes text NOT NULL,
    total_comisiones numeric(15,2) NOT NULL DEFAULT 0.00,
    total_albo numeric(15,2) NOT NULL DEFAULT 0.00,
    total_albo_ip numeric(15,2) NOT NULL DEFAULT 0.00,
    total_guias numeric(15,2) NOT NULL DEFAULT 0.00,
    total_puertos numeric(15,2) NOT NULL DEFAULT 0.00,
    total_otros numeric(15,2) NOT NULL DEFAULT 0.00,
    total_facturas numeric(15,2) NOT NULL DEFAULT 0.00, 
    total_general numeric(15,2) NOT NULL DEFAULT 0.00,  
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT resumen_mensual_pkey PRIMARY KEY (mes)
);

-- ============================================================================
-- 3. REGISTROS INICIALES DE CONFIGURACIÓN (Seeds actualizados según tus capturas)
-- ============================================================================
INSERT INTO public.config_nits (nit, proveedor, codigo)
VALUES 
    ('120585022', 'ALBO', '20934'),
    ('161462027', 'DAB', '70742')
ON CONFLICT (nit) DO UPDATE 
SET proveedor = EXCLUDED.proveedor, codigo = EXCLUDED.codigo;

-- Seed de Comisiones por Rango
INSERT INTO public.config_comisiones_minera (cif_usd_min, cif_usd_max, porcentaje_comision, comision_fija, descripcion)
VALUES
    (0.00, 35000.00, 0.0000, 600.00, 'Tarifa Fija de Bs 600.00'),
    (35000.01, 500000.00, 0.0030, 0.00, '0.30% de Comisión sobre CIF Bs'),
    (500000.01, 1000000000.00, 0.0025, 0.00, '0.25% de Comisión sobre CIF Bs')
ON CONFLICT (id) DO NOTHING;

-- Seed de Comisiones Especiales
INSERT INTO public.config_comisiones_especiales (tipo_operacion, comision_fija, descripcion)
VALUES
    ('EXP', 700.00, 'Despachos de Exportación, Exportación temporal y reimportaciones')
ON CONFLICT (tipo_operacion) DO UPDATE 
SET comision_fija = EXCLUDED.comision_fija, descripcion = EXCLUDED.descripcion;

-- ============================================================================
-- 4. FUNCIONES Y LÓGICA DE NEGOCIO
-- ============================================================================

-- A. Extracción inteligente del NIT desde el enlace del QR (parámetro nit=...)
CREATE OR REPLACE FUNCTION public.extraer_nit_from_qr(qr_text text)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    v_nit text;
BEGIN
    IF qr_text IS NULL OR qr_text = '' THEN
        RETURN NULL;
    END IF;
    
    IF qr_text LIKE '%nit=%' THEN
        v_nit := substring(qr_text from 'nit=([0-9]+)');
        IF v_nit IS NOT NULL THEN
            RETURN v_nit;
        END IF;
    END IF;
    
    IF qr_text LIKE '%|%' THEN
        RETURN split_part(qr_text, '|', 1);
    END IF;
    
    IF qr_text ~ '^[0-9]+$' THEN
        RETURN qr_text;
    END IF;
    
    RETURN NULL;
END;
$$;

-- B. Transformación de n_declaracion de importaciones (ej. DI-2026-543-2023821 -> 5432026D2023821)
CREATE OR REPLACE FUNCTION public.transformar_declaracion(decl_text text)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    v_parts text[];
BEGIN
    IF decl_text IS NULL OR decl_text = '' OR decl_text = '-' THEN
        RETURN '-';
    END IF;
    
    decl_text := replace(trim(decl_text), ' ', '-');
    v_parts := string_to_array(decl_text, '-');
    
    IF array_length(v_parts, 1) = 4 THEN
        RETURN v_parts[3] || v_parts[2] || 'D' || v_parts[4];
    END IF;
    
    IF array_length(v_parts, 1) = 3 THEN
        RETURN v_parts[2] || v_parts[1] || 'D' || v_parts[3];
    END IF;
    
    RETURN regexp_replace(decl_text, '[^a-zA-Z0-9]', '', 'g');
END;
$$;

-- C. Comparación inteligente y limpia de declaraciones aduaneras
CREATE OR REPLACE FUNCTION public.comparar_declaraciones(decl_imp text, doc_fact text)
RETURNS boolean LANGUAGE plpgsql AS $$
DECLARE
    v_clean_imp text;
    v_clean_fact text;
BEGIN
    IF decl_imp IS NULL OR decl_imp = '' OR decl_imp = '-' OR doc_fact IS NULL OR doc_fact = '' OR doc_fact = '-' THEN
        RETURN FALSE;
    END IF;
    
    v_clean_imp := public.transformar_declaracion(decl_imp);
    v_clean_imp := regexp_replace(upper(trim(v_clean_imp)), '[^A-Z0-9]', '', 'g');
    v_clean_fact := regexp_replace(upper(trim(doc_fact)), '[^A-Z0-9]', '', 'g');
    
    RETURN (v_clean_imp = v_clean_fact OR position(v_clean_imp in v_clean_fact) > 0 OR position(v_clean_fact in v_clean_imp) > 0);
END;
$$;

-- D. Comparación inteligente y limpia de guías (ignora prefijos MAWB, HAWB, etc.)
CREATE OR REPLACE FUNCTION public.comparar_guias(guia_imp text, ref_fact text)
RETURNS boolean LANGUAGE plpgsql AS $$
DECLARE
    v_clean_imp text;
    v_clean_fact text;
BEGIN
    IF guia_imp IS NULL OR guia_imp = '' OR guia_imp = '-' OR ref_fact IS NULL OR ref_fact = '' OR ref_fact = '-' THEN
        RETURN FALSE;
    END IF;
    
    v_clean_imp := regexp_replace(upper(trim(guia_imp)), '[^A-Z0-9]', '', 'g');
    v_clean_fact := regexp_replace(upper(trim(ref_fact)), '[^A-Z0-9]', '', 'g');
    v_clean_fact := regexp_replace(v_clean_fact, '^(MAWB|HAWB|GUIA|AWB)', '', 'i');
    
    RETURN (v_clean_imp = v_clean_fact OR position(v_clean_imp in v_clean_fact) > 0 OR position(v_clean_fact in v_clean_imp) > 0);
END;
$$;

-- E. LÓGICA DE RECALCULACIÓN DE RESUMEN MENSUAL
CREATE OR REPLACE FUNCTION public.recalcular_resumen_mensual()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    TRUNCATE TABLE public.resumen_mensual;
    
    INSERT INTO public.resumen_mensual (
        mes,
        total_comisiones,
        total_albo,
        total_albo_ip,
        total_guias,
        total_puertos,
        total_otros,
        total_facturas,
        total_general,
        updated_at
    )
    SELECT 
        mes,
        coalesce(sum(comision_bob), 0.00) as total_comisiones,
        coalesce(sum(albo_monto), 0.00) as total_albo,
        coalesce(sum(ip_monto), 0.00) as total_albo_ip,
        coalesce(sum(guias_monto), 0.00) as total_guias,
        coalesce(sum(puertos_monto), 0.00) as total_puertos,
        coalesce(sum(otros_monto), 0.00) as total_otros,
        coalesce(sum(coalesce(albo_monto, 0.00) + coalesce(ip_monto, 0.00) + coalesce(guias_monto, 0.00) + coalesce(puertos_monto, 0.00) + coalesce(otros_monto, 0.00)), 0.00) as total_facturas,
        coalesce(sum(coalesce(comision_bob, 0.00) + coalesce(albo_monto, 0.00) + coalesce(ip_monto, 0.00) + coalesce(guias_monto, 0.00) + coalesce(puertos_monto, 0.00) + coalesce(otros_monto, 0.00)), 0.00) as total_general,
        now()
    FROM public.mtodo
    WHERE mes <> '-'
    GROUP BY mes;
END;
$$;

-- F. LÓGICA DE RECALCULACIÓN DE CARPETA (Whitelisting y matching dinámico de NITs y Verificaciones)
CREATE OR REPLACE FUNCTION public.recalcular_carpeta_matriz(target_n_referencia text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    v_importacion_id bigint;
    v_total_cif text;
    v_tipo_cambio numeric;
    v_tc_aplicado numeric;
    v_cif_bob numeric;
    v_cif_usd numeric;
    
    -- Variables para el cálculo de la comisión
    v_porcentaje_comision numeric;
    v_comision_fija numeric;
    v_comision_bob numeric;
    v_porcentaje_str text;
    
    -- variables para ALBO/DAB
    v_albo_cod text;
    v_albo_factura text;
    v_albo_fecha text;
    v_albo_enlace text;
    v_albo_monto numeric;
    v_albo_n_declaracion_imp text;
    v_albo_doc_aduanero_fac text;
    v_albo_verificado text;
    
    -- variables para IP
    v_ip_cod text;
    v_ip_factura text;
    v_ip_fecha text;
    v_ip_enlace text;
    v_ip_monto numeric;
    v_ip_examen_previo_imp text;
    v_ip_doc_aduanero_fac text;
    v_ip_verificado text;
    
    -- variables para GUIAS
    v_guias_cod text;
    v_guias_factura text;
    v_guias_fecha text;
    v_guias_enlace text;
    v_guias_monto numeric;
    v_guias_guia_embarque_imp text;
    v_guias_ref_guia_fac text;
    v_guias_verificado text;
    
    -- variables para PUERTOS
    v_puertos_comprobante text;
    v_puertos_fecha text;
    v_puertos_monto numeric;
    
    -- variables para Tributos
    v_gravamen numeric(15,2);
    v_iva numeric(15,2);
    v_total_tributos numeric(15,2);
    
    -- variables para OTROS
    v_otros_cod text;
    v_otros_factura text;
    v_otros_fecha text;
    v_otros_enlace text;
    v_otros_monto numeric;
    
    -- Datos de la importación
    v_fecha_aceptacion text;
    v_mes text;
    v_date date;
    v_nit_importador text;
    v_n_declaracion text;
    v_modalidad text;
    v_estado_liquidacion text;
    v_oi text;
    v_examen_previo text;
    v_guia_embarque text;
    
    -- Overrides manuales
    v_comision_manual numeric;
    v_dim_regularizada text;
    v_dim_reg_status text;
    
    -- Planilla Excel
    v_ref_excel text;
    v_fecha_excel text;
    v_debito_excel numeric(15,2);
BEGIN
    -- 1. Obtener detalles de la importación, filtrando SOLO por MINERA SAN CRISTOBAL S.A. o su NIT
    SELECT id, total_cif, tipo_cambio, fecha_aceptacion, n_declaracion, modalidad, estado_liquidacion, oi, nit_importador, examen_previo, guia_embarque,
           coalesce(nullif(regexp_replace(gravamen, '[^0-9.]', '', 'g'), ''), '0')::numeric,
           coalesce(nullif(regexp_replace(iva, '[^0-9.]', '', 'g'), ''), '0')::numeric,
           coalesce(nullif(regexp_replace(total_tributos, '[^0-9.]', '', 'g'), ''), '0')::numeric
    INTO v_importacion_id, v_total_cif, v_tipo_cambio, v_fecha_aceptacion, v_n_declaracion, v_modalidad, v_estado_liquidacion, v_oi, v_nit_importador, v_examen_previo, v_guia_embarque,
         v_gravamen, v_iva, v_total_tributos
    FROM public.importaciones
    WHERE n_referencia = target_n_referencia
      AND (razon_social ILIKE '%MINERA SAN CRISTOBAL%' OR nit_importador = '1020415021')
    LIMIT 1;
    
    IF v_importacion_id IS NULL THEN
        DELETE FROM public.mtodo WHERE interno = target_n_referencia;
        PERFORM public.recalcular_resumen_mensual();
        RETURN;
    END IF;
    
    -- 2. Calcular mes (abbreviación ENE-2026, JUL-2026, etc.) con parseador robusto
    BEGIN
        IF v_fecha_aceptacion IS NOT NULL AND v_fecha_aceptacion <> '' AND v_fecha_aceptacion <> '-' THEN
            IF v_fecha_aceptacion ~ '^[0-9]{4}-' THEN
                v_date := to_date(v_fecha_aceptacion, 'YYYY-MM-DD');
            ELSIF v_fecha_aceptacion ~ '^[0-9]{2}/' THEN
                v_date := to_date(v_fecha_aceptacion, 'DD/MM/YYYY');
            ELSE
                v_date := v_fecha_aceptacion::date;
            END IF;
            
            v_mes := CASE extract(month from v_date)
                WHEN 1 THEN 'ENE'
                WHEN 2 THEN 'FEB'
                WHEN 3 THEN 'MAR'
                WHEN 4 THEN 'ABR'
                WHEN 5 THEN 'MAY'
                WHEN 6 THEN 'JUN'
                WHEN 7 THEN 'JUL'
                WHEN 8 THEN 'AGO'
                WHEN 9 THEN 'SEP'
                WHEN 10 THEN 'OCT'
                WHEN 11 THEN 'NOV'
                WHEN 12 THEN 'DIC'
                ELSE '-'
            END || '-' || to_char(v_date, 'YYYY');
        ELSE
            v_mes := '-';
        END IF;
    EXCEPTION WHEN OTHERS THEN
        v_mes := '-';
    END;

    -- 3. Calcular valores financieros básicos
    v_tc_aplicado := coalesce(nullif(v_tipo_cambio, 0), 6.96);
    v_cif_bob := coalesce(nullif(regexp_replace(v_total_cif, '[^0-9.]', '', 'g'), ''), '0')::numeric;
    v_cif_usd := v_cif_bob / v_tc_aplicado;
    
    -- Buscar comisión en tablas configurables
    SELECT comision_fija, tipo_operacion 
    INTO v_comision_fija, v_porcentaje_str
    FROM public.config_comisiones_especiales
    WHERE v_oi ILIKE '%' || tipo_operacion || '%'
    LIMIT 1;
    
    IF FOUND THEN
        v_comision_bob := v_comision_fija;
        v_porcentaje_str := 'Fijo: ' || v_porcentaje_str;
    ELSE
        SELECT porcentaje_comision, comision_fija 
        INTO v_porcentaje_comision, v_comision_fija
        FROM public.config_comisiones_minera
        WHERE v_cif_usd >= cif_usd_min AND v_cif_usd <= cif_usd_max
        LIMIT 1;
        
        IF NOT FOUND THEN
            v_comision_bob := 600.00;
            v_porcentaje_str := 'Tarifa Fija';
        ELSIF v_comision_fija > 0 THEN
            v_comision_bob := v_comision_fija;
            v_porcentaje_str := 'Tarifa Fija';
        ELSE
            v_comision_bob := v_cif_bob * v_porcentaje_comision;
            v_porcentaje_str := to_char(v_porcentaje_comision * 100, 'FM990.00') || '%';
        END IF;
    END IF;
    
    -- Aplicar override de ajuste manual de comisión si existe
    SELECT comision INTO v_comision_manual
    FROM public.historial_datos_minera
    WHERE dim_id = v_importacion_id OR interno = target_n_referencia
    LIMIT 1;
    
    IF v_comision_manual IS NOT NULL THEN
        v_comision_bob := v_comision_manual;
        v_porcentaje_str := 'Manual';
    END IF;
    
    -- Obtener estado de regularización
    SELECT dim_regularizada INTO v_dim_regularizada
    FROM public.regularizaciones_dims
    WHERE interno = target_n_referencia
    LIMIT 1;
    
    IF FOUND AND v_dim_regularizada = 'OK' THEN
        v_dim_reg_status := 'OK';
    ELSE
        v_dim_reg_status := '-';
    END IF;
    
    -- 4. Consolidar ALBO / DAB (Extrayendo el NIT desde enlace_qr / f.nit para relacionar el código)
    SELECT 
        sum(f.monto),
        string_agg(f.n_factura, ', '),
        string_agg(f.fecha, ', '),
        string_agg(coalesce(f.codigo_qr, '-'), ', '),
        string_agg(distinct coalesce(cn.codigo, public.extraer_nit_from_qr(f.codigo_qr), f.nit, 'S/C'), ', '),
        string_agg(distinct coalesce(f.doc_aduanero, '-'), ', ')
    INTO v_albo_monto, v_albo_factura, v_albo_fecha, v_albo_enlace, v_albo_cod, v_albo_doc_aduanero_fac
    FROM public.facturas f
    LEFT JOIN public.config_nits cn ON cn.nit = coalesce(public.extraer_nit_from_qr(f.codigo_qr), f.nit)
    WHERE f.importacion_id = v_importacion_id
      AND (((f.tipo ILIKE '%ALBO%' AND f.tipo NOT ILIKE '%IP%' AND f.tipo NOT ILIKE '%INSPECCION%') OR f.tipo ILIKE '%DAB%'));

    -- Transformación y Verificación ALBO
    v_albo_n_declaracion_imp := public.transformar_declaracion(v_n_declaracion);
    
    IF v_modalidad ILIKE '%ANTICIPAD%' THEN
        v_albo_verificado := '-';
    ELSIF v_albo_monto IS NULL OR v_albo_monto = 0 THEN
        v_albo_verificado := '-';
    ELSIF public.comparar_declaraciones(v_n_declaracion, v_albo_doc_aduanero_fac) THEN
        v_albo_verificado := 'VERIFICADO';
    ELSE
        v_albo_verificado := 'NO VERIFICADO';
    END IF;

    -- 5. Consolidar Inspección Previa (IP)
    SELECT 
        sum(f.monto),
        string_agg(f.n_factura, ', '),
        string_agg(f.fecha, ', '),
        string_agg(coalesce(f.codigo_qr, '-'), ', '),
        string_agg(distinct coalesce(cn.codigo, public.extraer_nit_from_qr(f.codigo_qr), f.nit, 'S/C'), ', '),
        string_agg(distinct coalesce(f.doc_aduanero, '-'), ', ')
    INTO v_ip_monto, v_ip_factura, v_ip_fecha, v_ip_enlace, v_ip_cod, v_ip_doc_aduanero_fac
    FROM public.facturas f
    LEFT JOIN public.config_nits cn ON cn.nit = coalesce(public.extraer_nit_from_qr(f.codigo_qr), f.nit)
    WHERE f.importacion_id = v_importacion_id
      AND (f.tipo ILIKE '%ALBO IP%' OR f.tipo ILIKE '%INSPECCION%');

    -- Estandarización y Verificación IP
    v_ip_examen_previo_imp := coalesce(v_examen_previo, '-');
    
    IF v_ip_monto IS NULL OR v_ip_monto = 0 THEN
        v_ip_verificado := '-';
    ELSIF v_ip_examen_previo_imp = '-' THEN
        v_ip_verificado := 'SIN EXAMEN PREVIO';
    ELSIF position(v_ip_examen_previo_imp in coalesce(v_ip_doc_aduanero_fac, '')) > 0 THEN
        v_ip_verificado := 'VERIFICADO';
    ELSE
        v_ip_verificado := 'NO VERIFICADO';
    END IF;

    -- 6. Consolidar Guías
    SELECT 
        sum(f.monto),
        string_agg(f.n_factura, ', '),
        string_agg(f.fecha, ', '),
        string_agg(coalesce(f.codigo_qr, '-'), ', '),
        string_agg(distinct coalesce(cn.codigo, public.extraer_nit_from_qr(f.codigo_qr), f.nit, 'S/C'), ', '),
        string_agg(distinct coalesce(f.ref_guia, '-'), ', ')
    INTO v_guias_monto, v_guias_factura, v_guias_fecha, v_guias_enlace, v_guias_cod, v_guias_ref_guia_fac
    FROM public.facturas f
    LEFT JOIN public.config_nits cn ON cn.nit = coalesce(public.extraer_nit_from_qr(f.codigo_qr), f.nit)
    WHERE f.importacion_id = v_importacion_id
      AND (f.tipo ILIKE '%GUIA%');

    -- Estandarización y Verificación GUÍA
    v_guias_guia_embarque_imp := coalesce(v_guia_embarque, '-');
    
    IF v_modalidad ILIKE '%ANTICIPAD%' THEN
        v_guias_verificado := '-';
    ELSIF v_guias_monto IS NULL OR v_guias_monto = 0 THEN
        v_guias_verificado := '-';
    ELSIF v_guias_guia_embarque_imp = '-' THEN
        v_guias_verificado := 'SIN GUIA EMBARQUE';
    ELSIF public.comparar_guias(v_guias_guia_embarque_imp, v_guias_ref_guia_fac) THEN
        v_guias_verificado := 'VERIFICADO';
    ELSE
        v_guias_verificado := 'NO VERIFICADO';
    END IF;

    -- 7. Consolidar Puertos
    SELECT 
        sum(g.monto),
        string_agg(g.comprobante, ', '),
        string_agg(g.fecha, ', ')
    INTO v_puertos_monto, v_puertos_comprobante, v_puertos_fecha
    FROM public.gastos_puertos_manual g
    WHERE g.importacion_id = v_importacion_id;

    -- 8. Consolidar Otros
    SELECT 
        sum(f.monto),
        string_agg(f.n_factura, ', '),
        string_agg(f.fecha, ', '),
        string_agg(coalesce(f.codigo_qr, '-'), ', '),
        string_agg(distinct coalesce(cn.codigo, public.extraer_nit_from_qr(f.codigo_qr), f.nit, 'S/C'), ', ')
    INTO v_otros_monto, v_otros_factura, v_otros_fecha, v_otros_enlace, v_otros_cod
    FROM public.facturas f
    LEFT JOIN public.config_nits cn ON cn.nit = coalesce(public.extraer_nit_from_qr(f.codigo_qr), f.nit)
    WHERE f.importacion_id = v_importacion_id
      AND NOT (((f.tipo ILIKE '%ALBO%' AND f.tipo NOT ILIKE '%IP%' AND f.tipo NOT ILIKE '%INSPECCION%') OR f.tipo ILIKE '%DAB%'))
      AND NOT (f.tipo ILIKE '%ALBO IP%' OR f.tipo ILIKE '%INSPECCION%')
      AND NOT (f.tipo ILIKE '%GUIA%');

    -- 8.5 Obtener datos de planilla excel
    SELECT ref_excel, fecha_excel, debito_excel INTO v_ref_excel, v_fecha_excel, v_debito_excel
    FROM public.historial_datos_minera
    WHERE interno = target_n_referencia
    LIMIT 1;

    -- 9. Insertar o Actualizar registro en la tabla física "mtodo"
    INSERT INTO public.mtodo (
        interno, importacion_id, fecha_dim, mes, nit_cliente, dim_n_ro, modalidad, dim_reg, oi,
        tipo_cambio, cif_usd, porcentaje_comision, valor_cif_bs, comision_bob,
        gravamen, iva, total_tributos,
        
        -- PLANILLA EXCEL
        ref_excel, fecha_excel, debito_excel,
        
        -- ALBO / DAB
        albo_monto, albo_factura, albo_fecha, albo_enlace, albo_cod,
        albo_n_declaracion_imp, albo_doc_aduanero_fac, albo_verificado,
        
        -- INSPECCION PREVIA (IP)
        ip_monto, ip_factura, ip_fecha, ip_enlace, ip_cod,
        ip_examen_previo_imp, ip_doc_aduanero_fac, ip_verificado,
        
        -- GUÍAS
        guias_monto, guias_factura, guias_fecha, guias_enlace, guias_cod,
        guias_guia_embarque_imp, guias_ref_guia_fac, guias_verificado,
        
        -- PUERTOS
        puertos_monto, puertos_comprobante, puertos_fecha,
        
        -- OTROS
        otros_monto, otros_factura, otros_fecha, otros_enlace, otros_cod,
        updated_at
    ) VALUES (
        target_n_referencia,
        v_importacion_id,
        v_fecha_aceptacion,
        v_mes,
        coalesce(v_nit_importador, '1020415021'),
        v_n_declaracion,
        v_modalidad,
        v_dim_reg_status,
        v_oi,
        coalesce(to_char(v_tc_aplicado, 'FM9990.00'), '-'),
        coalesce(to_char(v_cif_usd, 'FM9999990.00'), '-'),
        v_porcentaje_str,
        coalesce(v_total_cif, '-'),
        v_comision_bob,
        v_gravamen, v_iva, v_total_tributos,
        
        -- PLANILLA EXCEL
        v_ref_excel, v_fecha_excel, v_debito_excel,
        
        -- ALBO
        v_albo_monto, v_albo_factura, v_albo_fecha, v_albo_enlace, v_albo_cod,
        v_albo_n_declaracion_imp, v_albo_doc_aduanero_fac, v_albo_verificado,
        
        -- IP
        v_ip_monto, v_ip_factura, v_ip_fecha, v_ip_enlace, v_ip_cod,
        v_ip_examen_previo_imp, v_ip_doc_aduanero_fac, v_ip_verificado,
        
        -- GUIA
        v_guias_monto, v_guias_factura, v_guias_fecha, v_guias_enlace, v_guias_cod,
        v_guias_guia_embarque_imp, v_guias_ref_guia_fac, v_guias_verificado,
        
        -- PUERTOS
        v_puertos_monto, v_puertos_comprobante, v_puertos_fecha,
        
        -- OTROS
        v_otros_monto, v_otros_factura, v_otros_fecha, v_otros_enlace, v_otros_cod,
        now()
    )
    ON CONFLICT (interno) DO UPDATE SET
        importacion_id = EXCLUDED.importacion_id,
        fecha_dim = EXCLUDED.fecha_dim,
        mes = EXCLUDED.mes,
        nit_cliente = EXCLUDED.nit_cliente,
        dim_n_ro = EXCLUDED.dim_n_ro,
        modalidad = EXCLUDED.modalidad,
        dim_reg = EXCLUDED.dim_reg,
        oi = EXCLUDED.oi,
        tipo_cambio = EXCLUDED.tipo_cambio,
        cif_usd = EXCLUDED.cif_usd,
        porcentaje_comision = EXCLUDED.porcentaje_comision,
        valor_cif_bs = EXCLUDED.valor_cif_bs,
        comision_bob = EXCLUDED.comision_bob,
        gravamen = EXCLUDED.gravamen,
        iva = EXCLUDED.iva,
        total_tributos = EXCLUDED.total_tributos,
        
        -- PLANILLA EXCEL
        ref_excel = EXCLUDED.ref_excel,
        fecha_excel = EXCLUDED.fecha_excel,
        debito_excel = EXCLUDED.debito_excel,
        
        -- PRESERVAR VERIFICACIONES
        verificado_suma = coalesce(mtodo.verificado_suma, 'NO VERIFICADO'),
        verificado_saldos = coalesce(mtodo.verificado_saldos, 'NO VERIFICADO'),
        
        -- ALBO
        albo_monto = EXCLUDED.albo_monto,
        albo_factura = EXCLUDED.albo_factura,
        albo_fecha = EXCLUDED.albo_fecha,
        albo_enlace = EXCLUDED.albo_enlace,
        albo_cod = EXCLUDED.albo_cod,
        albo_n_declaracion_imp = EXCLUDED.albo_n_declaracion_imp,
        albo_doc_aduanero_fac = EXCLUDED.albo_doc_aduanero_fac,
        albo_verificado = EXCLUDED.albo_verificado,
        
        -- IP
        ip_monto = EXCLUDED.ip_monto,
        ip_factura = EXCLUDED.ip_factura,
        ip_fecha = EXCLUDED.ip_fecha,
        ip_enlace = EXCLUDED.ip_enlace,
        ip_cod = EXCLUDED.ip_cod,
        ip_examen_previo_imp = EXCLUDED.ip_examen_previo_imp,
        ip_doc_aduanero_fac = EXCLUDED.ip_doc_aduanero_fac,
        ip_verificado = EXCLUDED.ip_verificado,
        
        -- GUIAS
        guias_monto = EXCLUDED.guias_monto,
        guias_factura = EXCLUDED.guias_factura,
        guias_fecha = EXCLUDED.guias_fecha,
        guias_enlace = EXCLUDED.guias_enlace,
        guias_cod = EXCLUDED.guias_cod,
        guias_guia_embarque_imp = EXCLUDED.guias_guia_embarque_imp,
        guias_ref_guia_fac = EXCLUDED.guias_ref_guia_fac,
        guias_verificado = EXCLUDED.guias_verificado,
        
        -- PUERTOS
        puertos_monto = EXCLUDED.puertos_monto,
        puertos_comprobante = EXCLUDED.puertos_comprobante,
        puertos_fecha = EXCLUDED.puertos_fecha,
        
        -- OTROS
        otros_monto = EXCLUDED.otros_monto,
        otros_factura = EXCLUDED.otros_factura,
        otros_fecha = EXCLUDED.otros_fecha,
        otros_enlace = EXCLUDED.otros_enlace,
        otros_cod = EXCLUDED.otros_cod,
        updated_at = now();

    -- Recalcular resumen
    PERFORM public.recalcular_resumen_mensual();
END;
$$;

-- ============================================================================
-- 5. VISTA DE CONSULTA FINAL CON NOMBRES DE COLUMNA EXACTOS
-- ============================================================================
CREATE OR REPLACE VIEW public.v_matriz_liquidacion_horizontal AS
SELECT 
    interno AS INTERNO,
    importacion_id,
    coalesce(fecha_dim, '-') AS FECHA_DIM,
    coalesce(mes, '-') AS MES, 
    coalesce(nit_cliente, '-') AS NIT_CLIENTE, 
    coalesce(dim_n_ro, '-') AS DIM_N_RO,
    coalesce(modalidad, '-') AS MODALIDAD,
    coalesce(dim_reg, '-') AS DIM_REG,
    coalesce(oi, '-') AS OI,
    coalesce(tipo_cambio, '-') AS TIPO_CAMBIO,
    coalesce(cif_usd, '-') AS CIF_USD,
    coalesce(porcentaje_comision, '-') AS PORCENTAJE_COMISION,
    coalesce(valor_cif_bs, '-') AS VALOR_CIF_BS,
    coalesce(to_char(comision_bob, 'FM9999990.00'), '-') AS COMISION_BS,
    coalesce(to_char(gravamen, 'FM9999990.00'), '-') AS GRAVAMEN,
    coalesce(to_char(iva, 'FM9999990.00'), '-') AS IVA,
    coalesce(to_char(total_tributos, 'FM9999990.00'), '-') AS TOTAL_TRIBUTOS,
    
    -- PLANILLA EXCEL
    coalesce(ref_excel, '-') AS REF_EXCEL,
    coalesce(fecha_excel, '-') AS FECHA_EXCEL,
    coalesce(to_char(debito_excel, 'FM9999990.00'), '-') AS DEBITO_EXCEL,
    
    -- VERIFICACIONES
    coalesce(verificado_suma, 'NO VERIFICADO') AS VERIFICADO_SUMA,
    coalesce(verificado_saldos, 'NO VERIFICADO') AS VERIFICADO_SALDOS,
    
    -- ALBO / DAB
    coalesce(to_char(albo_monto, 'FM9999990.00'), '-') AS "ALBO - DAB MONTO",
    coalesce(albo_factura, '-') AS ALBO_FACTURA,
    coalesce(albo_fecha, '-') AS ALBO_FECHA,
    coalesce(albo_enlace, '-') AS ENLACE_ALBO,
    coalesce(albo_cod, '-') AS "ALBO COD",
    coalesce(albo_n_declaracion_imp, '-') AS "n_declaracion (importaciones)",
    coalesce(albo_doc_aduanero_fac, '-') AS "doc_aduanero (facturas)",
    coalesce(albo_verificado, '-') AS "verificado albo",
    
    -- INSPECCION PREVIA (IP)
    coalesce(to_char(ip_monto, 'FM9999990.00'), '-') AS IP_MONTO,
    coalesce(ip_factura, '-') AS IP_FACTURA,
    coalesce(ip_fecha, '-') AS IP_FECHA,
    coalesce(ip_enlace, '-') AS IP_ALBO,
    coalesce(ip_cod, '-') AS "IP COD",
    coalesce(ip_examen_previo_imp, '-') AS "examen_previo (importaciones)",
    coalesce(ip_doc_aduanero_fac, '-') AS "doc_aduanero (facturas) ", 
    coalesce(ip_verificado, '-') AS "verificado ip",
    
    -- GUÍAS
    coalesce(to_char(guias_monto, 'FM9999990.00'), '-') AS GUIAS_MONTO,
    coalesce(guias_factura, '-') AS GUIAS_FACTURA,
    coalesce(guias_fecha, '-') AS GUIAS_FECHA,
    coalesce(guias_enlace, '-') AS GUIAS_ALBO,
    coalesce(guias_cod, '-') AS "GUIAS COD",
    coalesce(guias_guia_embarque_imp, '-') AS "guia_embarque (importaciones)",
    coalesce(guias_ref_guia_fac, '-') AS "ref_guia (facturas)",
    coalesce(guias_verificado, '-') AS "verificado guia",
    
    -- PUERTOS
    coalesce(to_char(puertos_monto, 'FM9999990.00'), '-') AS PUERTOS_MONTO,
    coalesce(puertos_comprobante, '-') AS PUERTO_COMPROBANTE,
    coalesce(puertos_fecha, '-') AS PUERTO_FECHA,
    
    -- OTROS
    coalesce(to_char(otros_monto, 'FM9999990.00'), '-') AS OTRO_MONTO,
    coalesce(otros_factura, '-') AS OTRO_FACTURA,
    coalesce(otros_fecha, '-') AS OTRO_FECHA,
    coalesce(otros_enlace, '-') AS OTRO_ALBO,
    coalesce(otros_cod, '-') AS "OTRO COD"
FROM public.mtodo;

-- ============================================================================
-- H. VISTA DE CONSULTA DEL RESUMEN MENSUAL CON FORMATO
-- ============================================================================
CREATE OR REPLACE VIEW public.v_resumen_mensual AS
SELECT 
    mes AS MES,
    coalesce(to_char(total_comisiones, 'FM9999990.00'), '-') AS TOTAL_COMISIONES,
    coalesce(to_char(total_albo, 'FM9999990.00'), '-') AS TOTAL_ALBO,
    coalesce(to_char(total_albo_ip, 'FM9999990.00'), '-') AS TOTAL_ALBO_IP,
    coalesce(to_char(total_guias, 'FM9999990.00'), '-') AS TOTAL_GUIAS,
    coalesce(to_char(total_puertos, 'FM9999990.00'), '-') AS TOTAL_PUERTOS,
    coalesce(to_char(total_otros, 'FM9999990.00'), '-') AS TOTAL_OTROS,
    coalesce(to_char(total_facturas, 'FM9999990.00'), '-') AS TOTAL_FACTURAS,
    coalesce(to_char(total_general, 'FM9999990.00'), '-') AS TOTAL_GENERAL
FROM public.resumen_mensual
ORDER BY 
    substring(mes from 5 for 4) DESC,
    CASE substring(mes from 1 for 3)
        WHEN 'ENE' THEN 1
        WHEN 'FEB' THEN 2
        WHEN 'MAR' THEN 3
        WHEN 'ABR' THEN 4
        WHEN 'MAY' THEN 5
        WHEN 'JUN' THEN 6
        WHEN 'JUL' THEN 7
        WHEN 'AGO' THEN 8
        WHEN 'SEP' THEN 9
        WHEN 'OCT' THEN 10
        WHEN 'NOV' THEN 11
        WHEN 'DIC' THEN 12
        ELSE 0
    END DESC;

-- ============================================================================
-- 6. TRIGGERS DE ACTUALIZACIÓN AUTOMÁTICA EN TIEMPO REAL
-- ============================================================================

CREATE OR REPLACE FUNCTION public.tg_recalcular_matriz_importaciones()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM public.recalcular_carpeta_matriz(OLD.n_referencia);
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        IF OLD.n_referencia IS DISTINCT FROM NEW.n_referencia THEN
            PERFORM public.recalcular_carpeta_matriz(OLD.n_referencia);
        END IF;
        PERFORM public.recalcular_carpeta_matriz(NEW.n_referencia);
        RETURN NEW;
    ELSE
        PERFORM public.recalcular_carpeta_matriz(NEW.n_referencia);
        RETURN NEW;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_recalcular_matriz_importaciones ON public.importaciones;
CREATE TRIGGER trg_recalcular_matriz_importaciones
AFTER INSERT OR UPDATE OR DELETE ON public.importaciones
FOR EACH ROW EXECUTE FUNCTION public.tg_recalcular_matriz_importaciones();

CREATE OR REPLACE FUNCTION public.tg_recalcular_matriz_facturas()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_n_ref text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        SELECT n_referencia INTO v_n_ref FROM public.importaciones WHERE id = OLD.importacion_id;
        IF v_n_ref IS NOT NULL THEN
            PERFORM public.recalcular_carpeta_matriz(v_n_ref);
        END IF;
        RETURN OLD;
    ELSE
        SELECT n_referencia INTO v_n_ref FROM public.importaciones WHERE id = NEW.importacion_id;
        IF v_n_ref IS NOT NULL THEN
            PERFORM public.recalcular_carpeta_matriz(v_n_ref);
        END IF;
        
        IF TG_OP = 'UPDATE' AND OLD.importacion_id IS DISTINCT FROM NEW.importacion_id THEN
            SELECT n_referencia INTO v_n_ref FROM public.importaciones WHERE id = OLD.importacion_id;
            IF v_n_ref IS NOT NULL THEN
                PERFORM public.recalcular_carpeta_matriz(v_n_ref);
            END IF;
        END IF;
        RETURN NEW;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_recalcular_matriz_facturas ON public.facturas;
CREATE TRIGGER trg_recalcular_matriz_facturas
AFTER INSERT OR UPDATE OR DELETE ON public.facturas
FOR EACH ROW EXECUTE FUNCTION public.tg_recalcular_matriz_facturas();

CREATE OR REPLACE FUNCTION public.tg_recalcular_matriz_puertos()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_n_ref text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        SELECT n_referencia INTO v_n_ref FROM public.importaciones WHERE id = OLD.importacion_id;
        IF v_n_ref IS NOT NULL THEN
            PERFORM public.recalcular_carpeta_matriz(v_n_ref);
        END IF;
        RETURN OLD;
    ELSE
        SELECT n_referencia INTO v_n_ref FROM public.importaciones WHERE id = NEW.importacion_id;
        IF v_n_ref IS NOT NULL THEN
            PERFORM public.recalcular_carpeta_matriz(v_n_ref);
        END IF;
        
        IF TG_OP = 'UPDATE' AND OLD.importacion_id IS DISTINCT FROM NEW.importacion_id THEN
            SELECT n_referencia INTO v_n_ref FROM public.importaciones WHERE id = OLD.importacion_id;
            IF v_n_ref IS NOT NULL THEN
                PERFORM public.recalcular_carpeta_matriz(v_n_ref);
            END IF;
        END IF;
        RETURN NEW;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_recalcular_matriz_puertos ON public.gastos_puertos_manual;
CREATE TRIGGER trg_recalcular_matriz_puertos
AFTER INSERT OR UPDATE OR DELETE ON public.gastos_puertos_manual
FOR EACH ROW EXECUTE FUNCTION public.tg_recalcular_matriz_puertos();

-- Triggers de configuración y manual overrides
CREATE OR REPLACE FUNCTION public.tg_recalcular_toda_la_matriz()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM public.inicializar_matriz_liquidacion();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.tg_recalcular_matriz_nits_modificados()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    r RECORD;
    v_nit text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_nit := OLD.nit;
    ELSE
        v_nit := NEW.nit;
    END IF;

    -- Recalcular solo las carpetas que tienen facturas con este NIT
    FOR r IN 
        SELECT DISTINCT imp.n_referencia 
        FROM public.importaciones imp
        JOIN public.facturas f ON f.importacion_id = imp.id
        WHERE (f.nit = v_nit OR public.extraer_nit_from_qr(f.codigo_qr) = v_nit)
          AND imp.n_referencia IS NOT NULL
          AND imp.n_referencia <> ''
    LOOP
        PERFORM public.recalcular_carpeta_matriz(r.n_referencia);
    END LOOP;
    
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_recalcular_toda_la_matriz_nits ON public.config_nits;
CREATE TRIGGER trg_recalcular_toda_la_matriz_nits
AFTER INSERT OR UPDATE OR DELETE ON public.config_nits
FOR EACH ROW EXECUTE FUNCTION public.tg_recalcular_matriz_nits_modificados();

DROP TRIGGER IF EXISTS trg_recalcular_toda_la_matriz_comisiones ON public.config_comisiones_minera;
CREATE TRIGGER trg_recalcular_toda_la_matriz_comisiones
AFTER INSERT OR UPDATE OR DELETE ON public.config_comisiones_minera
FOR EACH STATEMENT EXECUTE FUNCTION public.tg_recalcular_toda_la_matriz();

DROP TRIGGER IF EXISTS trg_recalcular_toda_la_matriz_comisiones_esp ON public.config_comisiones_especiales;
CREATE TRIGGER trg_recalcular_toda_la_matriz_comisiones_esp
AFTER INSERT OR UPDATE OR DELETE ON public.config_comisiones_especiales
FOR EACH STATEMENT EXECUTE FUNCTION public.tg_recalcular_toda_la_matriz();

-- Triggers de overrides manuales (para reflejar cambios de comision o regularizacion de inmediato)
CREATE OR REPLACE FUNCTION public.tg_recalcular_matriz_overrides()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.interno IS NOT NULL THEN
            PERFORM public.recalcular_carpeta_matriz(OLD.interno);
        END IF;
        RETURN OLD;
    ELSE
        IF NEW.interno IS NOT NULL THEN
            PERFORM public.recalcular_carpeta_matriz(NEW.interno);
        END IF;
        RETURN NEW;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_recalcular_matriz_regularizaciones ON public.regularizaciones_dims;
CREATE TRIGGER trg_recalcular_matriz_regularizaciones
AFTER INSERT OR UPDATE OR DELETE ON public.regularizaciones_dims
FOR EACH ROW EXECUTE FUNCTION public.tg_recalcular_matriz_overrides();

DROP TRIGGER IF EXISTS trg_recalcular_matriz_historial ON public.historial_datos_minera;
CREATE TRIGGER trg_recalcular_matriz_historial
AFTER INSERT OR UPDATE OR DELETE ON public.historial_datos_minera
FOR EACH ROW EXECUTE FUNCTION public.tg_recalcular_matriz_overrides();

-- ============================================================================
-- 7. FUNCIÓN DE POBLADO DE HISTORIAL
-- ============================================================================
CREATE OR REPLACE FUNCTION public.inicializar_matriz_liquidacion()
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    r RECORD;
BEGIN
    -- Limpiar la tabla física
    TRUNCATE TABLE public.mtodo;
    
    -- Recalcular para cada importación del cliente Minera San Cristóbal
    FOR r IN 
        SELECT DISTINCT n_referencia 
        FROM public.importaciones
        WHERE (razon_social ILIKE '%MINERA SAN CRISTOBAL%' OR nit_importador = '1020415021')
          AND n_referencia IS NOT NULL 
          AND n_referencia <> ''
    LOOP
        PERFORM public.recalcular_carpeta_matriz(r.n_referencia);
    END LOOP;
    
    -- Recalcular resumen
    PERFORM public.recalcular_resumen_mensual();
END;
$$;

-- Ejecutar la inicialización para popular la tabla física inmediatamente
SELECT public.inicializar_matriz_liquidacion();

-- ============================================================================
-- 8. SCRIPT DE PRUEBA DE RECONSTRUCCIÓN CON DATOS EXISTENTES
-- ============================================================================
DO $$
DECLARE
    test_interno text := '1514-26';
    test_comision_check text;
    test_albo_monto_check text;
    test_guias_monto_check text;
BEGIN
    RAISE NOTICE '--- INICIANDO PRUEBA DE SINCRONIZACIÓN AUTOMÁTICA ---';
    PERFORM public.recalcular_carpeta_matriz(test_interno);
    
    SELECT porcentaje_comision, albo_monto::text, guias_monto::text
    INTO test_comision_check, test_albo_monto_check, test_guias_monto_check
    FROM public.mtodo
    WHERE interno = test_interno;
    
    RAISE NOTICE 'Carpeta 1514-26 -> Comision: %, Albo: % BOB, Guías: % BOB', 
                 test_comision_check, test_albo_monto_check, test_guias_monto_check;
    RAISE NOTICE '--- VERIFICACIÓN DE RECALCULACIÓN DE HISTORIAL COMPLETADA ---';
END $$;
